### PR TITLE
fixed winding and face culling to work with current version of amulet

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ianmaclarty** [comment]
Thanks for the PR. I did forget to update vertex meadow after fixing face winding in amulet, but I think your patch is wrong. I think it should be cw->front and ccw->back. This works for me in latest amulet. Does your patch work for you with latest amulet? It doesn't for me.

**Comment by ianmaclarty** [comment]
Oh wait, I see you changed the winding order on the generated tris, which explains why it works for you. That's not necessary, just change cw->front and ccw->back and you're good.

**Comment by ianmaclarty** [comment]
I've commit that change myself now - that's again for the PR!

**Comment by ghost** [comment]
hi! my reasoning was that the code would seem more straightforward if it says "back" faces are culled on the floor mesh and "front" faces on the ceiling, and since changing winding order doesn't break anything, why not do this for the sake of clarity. it worked fine for me, but maybe i overlooked something? i'm not very experienced in making such decisions... may i ask, why you preferred to just change culling options?

**Comment by ianmaclarty** [comment]
Only because it's a smaller change, really. To me it doesn't really matter if the floor is back or front face culled. Your solution was correct! I just prefer the fix that's a smaller change is all. Hope that makes sense!

**Comment by ghost** [comment]
ah, i see!

**Pull request closed without merging**
